const attribute = [
  'id',
  'categoryId',
  'itemName',
  'itemModel',
  'itemProductionNumber',
  'itemManufacturer',
  'yearOfOrigin',
  'color',
  'condition',
  'owner',
  'givenBy',
  'loanedBy',
  'description',
  'priceOfOrigin',
  'priceOfPurchase',
  'priceOfCurrent',
  'visibility',
  'userId',
  'updatedAt',
  'imagePath',
  'fileSystemId',
  'subCategoryId',
];
exports.module = attribute;
