const privacyPolicyDefinitionsPoints: string[] = [
  `Account means a unique account created for You to access our Service or parts of our Service.`,
  `Affiliate means an entity that controls, is controlled by or is under common control with a party, where "control" means ownership of 50% or more of the shares, equity interest or other securities entitled to vote for election of directors or other managing authority.`,
  `Company (referred to as either "the Company", "We", "Us" or "Our" in this Agreement) refers to miukama.`,
  `Cookies are small files that are placed on Your computer, mobile device or any other device by a website, containing the details of Your browsing history on that website among its many uses.`,
  `Country refers to: Madhya Pradesh, India`,
  `Device means any device that can access the Service such as a computer, a cellphone or a digital tablet.`,
  `Personal Data is any information that relates to an identified or identifiable individual.`,
  `Service refers to the Website.`,
  `Service Provider means any natural or legal person who processes the data on behalf of the Company. It refers to third-party companies or individuals employed by the Company to facilitate the Service, to provide the Service on behalf of the Company, to perform services related to the Service or to assist the Company in analyzing how the Service is used.`,
  `Third-party Social Media Service refers to any website or any social network website through which a User can log in or create an account to use the Service.`,
  `Usage Data refers to data collected automatically, either generated by the use of the Service or from the Service infrastructure itself (for example, the duration of a page visit).`,
  `You means the individual accessing or using the Service, or the company, or other legal entity on behalf of which such individual is accessing or using the Service, as applicable.`,
];

export default privacyPolicyDefinitionsPoints;
